export MYSQL_URL='mysql://user:password@tcp(localhost:port)/nama_db'

migrate-create:
	@ migrate create -ext sql -dir scripts/migrations -seq $(name)

migrate-up:
	@ migrate -database ${MYSQL_URL} -path scripts/migrations up

 migrate-down:
	@ migrate -database ${MYSQL_URL} -path scripts/migrations down
